### ISSUE TITLE
Empty scenario header causes exception

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibScenarios#187]
## Example

```markdown
# 
```

(there is a single space character after the `#`)

## Output

```
// failed to execute phase 'CodeGenerator' due to exception:
// java.lang.StringIndexOutOfBoundsException
// 	(12 internal calls)
// 	at org.fulib.scenarios.visitor.codegen.CodeGenerator.visit(CodeGenerator.java:51)
// 	at org.fulib.scenarios.ast.CompilationContext.accept(CompilationContext.java:24)
// 	(3 internal calls)
// 	at org.fulib.webapp.tool.Tools.scenarioc(Tools.java:83)
// 	at org.fulib.webapp.tool.Tools.genCompileRun(Tools.java:161)
// 	at org.fulib.webapp.tool.RunCodeGen.run(RunCodeGen.java:148)
// 	at org.fulib.webapp.tool.RunCodeGen.handle(RunCodeGen.java:50)
// 	(21 internal calls)
// Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
// 	(2 internal calls)
// 	at org.fulib.yaml.StrUtil.downFirstChar(StrUtil.java:55)
// 	at org.fulib.yaml.IdMap.generateUniqueKey(IdMap.java:203)
// 	at org.fulib.yaml.IdMap.addToObjIdMap(IdMap.java:188)
// 	at org.fulib.yaml.IdMap.putObject(IdMap.java:115)
// 	at org.fulib.yaml.YamlIdMap.collectObjects(YamlIdMap.java:746)
// 	at org.fulib.yaml.YamlIdMap.encode(YamlIdMap.java:777)
// 	at org.fulib.AbstractGenerator.saveNewClassModel(AbstractGenerator.java:186)
// 	at org.fulib.AbstractGenerator.generate(AbstractGenerator.java:110)
// 	at org.fulib.scenarios.visitor.codegen.CodeGenerator.visit(CodeGenerator.java:152)
// 	at org.fulib.scenarios.visitor.codegen.CodeGenerator.visit(CodeGenerator.java:31)
// 	at org.fulib.scenarios.ast.ScenarioGroup.accept(ScenarioGroup.java:26)
// 	at org.fulib.scenarios.visitor.codegen.CodeGenerator.lambda$visit$0(CodeGenerator.java:55)
// 	(9 internal calls)
```

**Comment by Clashsoft** [comment]
There are actually multiple issues that come together here:

1. fulibScenarios does not properly diagnose the empty scenario name. (#193)
2. fulib does not check the name of `FMethod`s. (https://github.com/fujaba/fulib/pull/72)
3. fulib does not define a `getId` method for `FMethod`s. (https://github.com/fujaba/fulib/pull/73)
4. fulibYaml cannot handle a `getName` or `getId` method returning an empty string. (https://github.com/fujaba/fulibYaml/issues/21)
